package io.github.akbarhusain.odata.runtime.query;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

/**
 * The lambda-predicate guard on {@link CollectionProperty#any}/{@link CollectionProperty#all}
 * exists to reject a bare property path that is not qualified by the lambda variable
 * ({@code any(x: Name eq 'a')}), which is invalid OData. It must not reject the legal
 * shapes that reference the bound variable itself or use a system path segment.
 *
 * <p>The guard only recognised "qualified" as <em>identifier</em> followed by {@code /}, so
 * it rejected three legal forms: the bound variable used as a bare path
 * ({@code x eq 'a'} — the canonical lambda body), a {@code $count} path segment, and
 * consequently every {@code contains(...)} nested in a lambda, since {@code contains}
 * renders {@code <path>/any(x: x eq <lit>)}. The identical predicate text was accepted by
 * the sibling {@link NavQuery#filter}, which never applied the guard.
 */
class CollectionPropertyLambdaGuardTest {

    static class Person {
    }

    static class Tag {
    }

    /** Mirrors the shape generated by {@code AbstractTypeGenerator} for a collection property. */
    static class TagFilterable {
        public final StringProperty<Tag> NAME = new StringProperty<>("x/Name", Tag.class);
        public final CollectionProperty<Tag, String, CollectionProperty.FilterableElement<String>, ?> NAMES =
                new CollectionProperty<>("x/Names", Tag.class, String.class,
                        CollectionProperty.FilterableElement::new, null, "Edm.String");
    }

    private static CollectionProperty<Person, Tag, TagFilterable, ?> tags() {
        return new CollectionProperty<>("Tags", Person.class, Tag.class, TagFilterable::new);
    }

    @Test
    void boundVariableUsedAsABarePathIsAccepted() {
        assertEquals("Tags/any(x: x eq 'a')",
                tags().any(t -> FilterExpression.<Tag>of("x eq 'a'")).toODataExpression());
        assertEquals("Tags/all(x: x eq 'a')",
                tags().all(t -> FilterExpression.<Tag>of("x eq 'a'")).toODataExpression());
    }

    @Test
    void countPathSegmentIsAccepted() {
        assertEquals("Tags/any(x: x/Names/$count gt 0)",
                tags().any(t -> t.NAMES.length().greaterThan(0)).toODataExpression());
    }

    @Test
    void containsNestedInAnyRenders() {
        assertEquals("Tags/any(x: x/Names/any(x1: x1 eq 'a'))",
                tags().any(t -> t.NAMES.contains("a")).toODataExpression());
        assertEquals("Tags/all(x: x/Names/any(x1: x1 eq 'a'))",
                tags().all(t -> t.NAMES.contains("a")).toODataExpression());
    }

    /**
     * The guard's original purpose: an unqualified property path inside a lambda is invalid
     * OData and must still be rejected. Widening acceptance must not remove the check.
     */
    @Test
    void unqualifiedPropertyPathIsStillRejected() {
        assertThrows(IllegalArgumentException.class,
                () -> tags().any(t -> FilterExpression.<Tag>of("Name eq 'a'")));
        assertThrows(IllegalArgumentException.class,
                () -> tags().any(t -> FilterExpression.<Tag>of("Name eq 'a' or Other gt 1")));
    }

    /**
     * The widened acceptance must not extend to depth-shaped names that nothing binds.
     * `x1 eq 'a'` in a predicate with no inner lambda references an unbound variable and
     * is invalid OData; accepting it because it "looks like" a nested alias would quietly
     * remove the check the guard exists to perform. Same for an arbitrary '$Name', which
     * is not a defined OData system segment.
     */
    @Test
    void unboundDepthShapedAndDollarNamesAreStillRejected() {
        assertThrows(IllegalArgumentException.class,
                () -> tags().any(t -> FilterExpression.<Tag>of("x1 eq 'a'")));
        assertThrows(IllegalArgumentException.class,
                () -> tags().any(t -> FilterExpression.<Tag>of("x2 eq 'a'")));
        assertThrows(IllegalArgumentException.class,
                () -> tags().any(t -> FilterExpression.<Tag>of("$Name eq 'a'")));
    }

    /** A nested lambda's alias IS bound, so it is accepted even though the shape matched. */
    @Test
    void nestedLambdaAliasIsAcceptedBecauseItIsActuallyBound() {
        // contains() renders the nested any() itself, so x1 is genuinely in scope here.
        assertEquals("Tags/any(x: x/Names/any(x1: x1 eq 'a'))",
                tags().any(t -> t.NAMES.contains("a")).toODataExpression());
    }

    /**
     * A qualified path stays accepted, and a constant-only predicate (no variable at all)
     * is legal OData and must not be rejected either.
     */
    @Test
    void qualifiedAndConstantPredicatesRemainAccepted() {
        assertEquals("Tags/any(x: x/Name eq 'a')",
                tags().any(t -> t.NAME.equalTo("a")).toODataExpression());
        assertEquals("Tags/any(x: true)",
                tags().any(t -> FilterExpression.<Tag>of("true")).toODataExpression());
    }

    /**
     * Sibling parity: the same predicate text must be judged the same way by the lambda
     * guard and by {@link NavQuery#filter}, which has no guard.
     */
    @Test
    void navQueryFilterAcceptsTheSamePredicatesTheLambdaGuardNowAccepts() {
        assertEquals("Trips($filter=x eq 'a')",
                NavQuery.<Person, Tag, Object>of("Trips")
                        .filter(FilterExpression.<Tag>of("x eq 'a'")).toODataExpand());
        assertEquals("Trips($filter=x/Names/$count gt 0)",
                NavQuery.<Person, Tag, Object>of("Trips")
                        .filter(FilterExpression.<Tag>of("x/Names/$count gt 0")).toODataExpand());
    }
}
