package io.github.akbarhusain.odata.core.generator;

import com.fasterxml.jackson.databind.ObjectMapper;
import io.github.akbarhusain.odata.core.model.CsdlModel;
import io.github.akbarhusain.odata.core.parser.StaxCsdlParser;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import javax.tools.JavaCompiler;
import javax.tools.JavaFileObject;
import javax.tools.StandardJavaFileManager;
import javax.tools.StandardLocation;
import javax.tools.ToolProvider;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.PrintWriter;
import java.io.StringWriter;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Stream;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Generated enums' JSON mapping: numeric payloads map by CSDL VALUE, not by ordinal
 * (Jackson's default) — values 1 and 4 on a 2-member enum make the ordinal mapping
 * observably wrong — and member-name strings keep working, INCLUDING members whose
 * CSDL names had to be sanitized into Java constants (the wire name round-trips via
 * the generated BY_NAME map).
 */
class EnumJsonDeserializationTest {

    private static final String METADATA = """
        <?xml version="1.0" encoding="utf-8"?>
        <edmx:Edmx Version="4.0" xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx">
          <edmx:DataServices>
            <Schema Namespace="TestNS" xmlns="http://docs.oasis-open.org/odata/ns/edm">
              <EnumType Name="Level">
                <Member Name="Low" Value="1"/>
                <Member Name="High" Value="4"/>
              </EnumType>
            </Schema>
          </edmx:DataServices>
        </edmx:Edmx>
        """;

    private static final String HOSTILE_METADATA = """
        <?xml version="1.0" encoding="utf-8"?>
        <edmx:Edmx Version="4.0" xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx">
          <edmx:DataServices>
            <Schema Namespace="TestNS" xmlns="http://docs.oasis-open.org/odata/ns/edm">
              <EnumType Name="E">
                <Member Name="a-b" Value="1"/>
                <Member Name="ok" Value="4"/>
              </EnumType>
            </Schema>
          </edmx:DataServices>
        </edmx:Edmx>
        """;

    @Test
    void numericPayloadsMapByValueNotOrdinal(@TempDir Path tempDir) throws Exception {
        String code = generateEnum(METADATA, "Level", tempDir);
        assertTrue(code.contains("@com.fasterxml.jackson.annotation.JsonCreator"),
                "generated enums must carry a @JsonCreator mapping numbers by value");

        try (var loader = loaderFor(tempDir)) {
            Class<Enum<?>> level = enumClass(loader, "Level");
            ObjectMapper mapper = new ObjectMapper();

            // Numeric 4 is ordinal 1 (High is index 1) AND value 4 — ambiguous for that one,
            // so use 1: ordinal 1 would be High, value 1 is Low. Value mapping => Low.
            Enum<?> fromNumber = mapper.readValue("1", level);
            assertEquals("Low", fromNumber.name(),
                    "numeric payloads must map by CSDL value, not ordinal");

            Enum<?> fromNumber4 = mapper.readValue("4", level);
            assertEquals("High", fromNumber4.name());

            // The OData v4 JSON string form keeps working
            Enum<?> fromName = mapper.readValue("\"High\"", level);
            assertEquals("High", fromName.name());
        }
    }

    @Test
    void sanitizedMemberNamesRoundTripWireNames(@TempDir Path tempDir) throws Exception {
        String code = generateEnum(HOSTILE_METADATA, "E", tempDir);
        assertTrue(code.contains("A_B(1L)"), "sanitized constant. Got:\n" + code);
        assertTrue(code.contains("BY_NAME"), "wire-name map generated for renamed members. Got:\n" + code);

        try (var loader = loaderFor(tempDir)) {
            Class<Enum<?>> e = enumClass(loader, "E");
            ObjectMapper mapper = new ObjectMapper();

            Enum<?> fromWireName = mapper.readValue("\"a-b\"", e);
            assertEquals("A_B", fromWireName.name(),
                    "the CSDL member name 'a-b' must deserialize to the sanitized constant");
            Enum<?> fromPlain = mapper.readValue("\"ok\"", e);
            assertEquals("ok", fromPlain.name(),
                    "un-sanitized members keep mapping by name");
            Enum<?> fromNumber = mapper.readValue("1", e);
            assertEquals("A_B", fromNumber.name(),
                    "numeric payloads still map by CSDL value");
        }
    }

    // ------------------------------------------------------------------
    // harness
    // ------------------------------------------------------------------

    private String generateEnum(String metadata, String enumName, Path tempDir) throws Exception {
        StaxCsdlParser parser = new StaxCsdlParser();
        CsdlModel model = parser.parse(new ByteArrayInputStream(metadata.getBytes(StandardCharsets.UTF_8)));
        var enumType = model.schemas().get(0).enumTypes().get(0);

        String code = new EnumGenerator("com.example.test").generate(enumType);

        Path srcDir = tempDir.resolve("src/com/example/test/enums");
        Files.createDirectories(srcDir);
        Files.writeString(srcDir.resolve(enumName + ".java"), code);

        JavaCompiler compiler = ToolProvider.getSystemJavaCompiler();
        assertNotNull(compiler, "Java compiler not available - run with a JDK");
        List<File> classpath = new ArrayList<>();
        Path m2 = Path.of(System.getProperty("user.home"), ".m2", "repository");
        try (Stream<Path> jars = Files.walk(m2)) {
            jars.filter(p -> p.toString().endsWith(".jar"))
                    .filter(p -> !p.toString().contains("-sources") && !p.toString().contains("-javadoc"))
                    .map(Path::toFile)
                    .forEach(classpath::add);
        }
        StringWriter out = new StringWriter();
        StandardJavaFileManager fm = compiler.getStandardFileManager(null, null, null);
        fm.setLocation(StandardLocation.CLASS_PATH, classpath);
        Path classesOut = tempDir.resolve("classes");
        Files.createDirectories(classesOut);
        fm.setLocation(StandardLocation.CLASS_OUTPUT, List.of(classesOut.toFile()));
        Iterable<? extends JavaFileObject> units = fm.getJavaFileObjects(
                srcDir.resolve(enumName + ".java").toFile());
        assertTrue(compiler.getTask(new PrintWriter(out), fm, null, null, null, units).call(),
                "generated enum must compile. Errors:\n" + out);
        return code;
    }

    private URLClassLoaderCompat loaderFor(Path tempDir) throws Exception {
        return new URLClassLoaderCompat(tempDir.resolve("classes"));
    }

    @SuppressWarnings("unchecked")
    private Class<Enum<?>> enumClass(ClassLoader loader, String simpleName) throws Exception {
        return (Class<Enum<?>>) Class.forName("com.example.test.enums." + simpleName, true, loader);
    }

    /** Tiny alias so test bodies read clearly. */
    private static final class URLClassLoaderCompat extends java.net.URLClassLoader {
        URLClassLoaderCompat(Path classesDir) throws Exception {
            super(new java.net.URL[]{classesDir.toUri().toURL()},
                    EnumJsonDeserializationTest.class.getClassLoader());
        }
    }
}
