package io.github.akbarhusain.odata.core.generator;

import io.github.akbarhusain.odata.core.model.CsdlModel;
import io.github.akbarhusain.odata.core.parser.StaxCsdlParser;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.ByteArrayInputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;

/**
 * M13: stale generated files must be cleaned when a later generate() call on the
 * same instance no longer produces them.
 */
class GeneratorMediumTest {

    private CsdlModel parse(String xml) throws Exception {
        return new StaxCsdlParser().parse(new ByteArrayInputStream(xml.getBytes(StandardCharsets.UTF_8)));
    }

    /**
     * M13: files generated by a previous {@code generate()} call on the same instance
     * must be deleted when a later call no longer produces them (entity renamed
     * Foo -> Bar leaves Foo.java on the classpath otherwise).
     */
    @Test
    void m13_staleFilesDeletedAcrossGenerateCalls(@TempDir Path tmp) throws Exception {
        String xml1 = """
                <?xml version="1.0" encoding="utf-8"?>
                <edmx:Edmx Version="4.0" xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx">
                  <edmx:DataServices>
                    <Schema Namespace="NS.Test" xmlns="http://docs.oasis-open.org/odata/ns/edm">
                      <EntityType Name="Foo"><Key><PropertyRef Name="Id"/></Key><Property Name="Id" Type="Edm.Int32" Nullable="false"/></EntityType>
                      <EntityContainer Name="Container"><EntitySet Name="Foos" EntityType="NS.Test.Foo"/></EntityContainer>
                    </Schema>
                  </edmx:DataServices>
                </edmx:Edmx>
                """;
        String xml3 = """
                <?xml version="1.0" encoding="utf-8"?>
                <edmx:Edmx Version="4.0" xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx">
                  <edmx:DataServices>
                    <Schema Namespace="NS.Test" xmlns="http://docs.oasis-open.org/odata/ns/edm">
                      <EntityType Name="Bar"><Key><PropertyRef Name="Id"/></Key><Property Name="Id" Type="Edm.Int32" Nullable="false"/></EntityType>
                      <EntityContainer Name="Container"><EntitySet Name="Bars" EntityType="NS.Test.Bar"/></EntityContainer>
                    </Schema>
                  </edmx:DataServices>
                </edmx:Edmx>
                """;
        // Same instance, two calls: the rename Foo -> Bar must not leave Foo.java behind.
        // (A fresh Generator per call is the Maven-plugin shape; the in-process shape is
        // what long-lived callers reuse.)
        Generator gen = new Generator(tmp, Map.of(), "com.test");
        gen.generate(parse(xml1));
        Path fooPath = tmp.resolve("com/test/entity/Foo.java");
        assertTrue(Files.exists(fooPath), "first generate should create Foo.java");

        gen.generate(parse(xml3));
        assertTrue(Files.exists(tmp.resolve("com/test/entity/Bar.java")), "Bar should exist");
        assertFalse(Files.exists(fooPath),
                "M13: stale Foo.java should have been deleted after the rename");
    }
}
